"""
Build the static site for Firebase Hosting.

Firebase Hosting serves static files only -- it cannot run Python. But a linear
regression is just its coefficients, so the entire model exports to a few
numbers and the prediction runs client-side in JavaScript with identical
results. No server, no Cloud Functions, no billing plan.

Run this after train_model.py so the deployed model never drifts from the
trained one:

    python train_model.py && python build_static.py && firebase deploy
"""

import json
import math
import os
import shutil

import pandas as pd

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PUBLIC = os.path.join(BASE_DIR, "public")


def main():
    with open(os.path.join(BASE_DIR, "model", "metrics.json")) as f:
        metrics = json.load(f)

    df = pd.read_csv(os.path.join(BASE_DIR, "data", "hdi_data.csv"))

    # Country lookup for the autofill dropdown. NaN -> null so JS can skip the
    # gaps rather than writing "NaN" into an input box.
    countries = []
    for _, r in df.sort_values("Country").iterrows():
        countries.append({
            "name": r["Country"],
            "le": None if pd.isna(r["Life_Expectancy"]) else float(r["Life_Expectancy"]),
            "es": None if pd.isna(r["Expected_Years_Schooling"]) else float(r["Expected_Years_Schooling"]),
            "ms": None if pd.isna(r["Mean_Years_Schooling"]) else float(r["Mean_Years_Schooling"]),
            "gni": None if pd.isna(r["GNI_per_Capita"]) else float(r["GNI_per_Capita"]),
            "hdi": None if pd.isna(r["HDI"]) else float(r["HDI"]),
        })

    c = metrics["coefficients"]
    model = {
        "coefficients": {
            "life_expectancy": c["Life_Expectancy"],
            "expected_schooling": c["Expected_Years_Schooling"],
            "mean_schooling": c["Mean_Years_Schooling"],
            "gni_log": c["GNI_log"],
        },
        "intercept": metrics["intercept"],
        "metrics": {
            "r2_test": metrics["r2_test"],
            "r2_train": metrics["r2_train"],
            "cv_r2": metrics["cv_r2"],
            "mae": metrics["mae"],
            "rmse": metrics["rmse"],
            "accuracy_pct": metrics["accuracy_pct"],
            "n_countries": metrics["n_countries"],
        },
    }

    os.makedirs(os.path.join(PUBLIC, "js"), exist_ok=True)
    os.makedirs(os.path.join(PUBLIC, "css"), exist_ok=True)

    with open(os.path.join(PUBLIC, "js", "model.js"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by build_static.py -- do not edit by hand.\n")
        f.write("// Re-run `python train_model.py && python build_static.py` to refresh.\n")
        f.write(f"export const MODEL = {json.dumps(model, indent=2)};\n\n")
        f.write(f"export const COUNTRIES = {json.dumps(countries, indent=1)};\n")

    shutil.copy(
        os.path.join(BASE_DIR, "static", "css", "style.css"),
        os.path.join(PUBLIC, "css", "style.css"),
    )

    img_src = os.path.join(BASE_DIR, "static", "images")
    img_dst = os.path.join(PUBLIC, "images")
    shutil.copytree(img_src, img_dst, dirs_exist_ok=True)

    # Sanity check: the JS must reproduce the Python model exactly. Recompute a
    # known prediction here using the exported numbers.
    le, es, ms, gni = 83.2, 18.2, 13.0, 64660  # Norway
    score = (
        model["intercept"]
        + model["coefficients"]["life_expectancy"] * le
        + model["coefficients"]["expected_schooling"] * es
        + model["coefficients"]["mean_schooling"] * ms
        + model["coefficients"]["gni_log"] * math.log(gni)
    )
    print(f"Exported model + {len(countries)} countries to public/js/model.js")
    print(f"Sanity check (Norway) from exported coefficients: {score:.3f}")
    print("Copied stylesheet and EDA figures into public/")


if __name__ == "__main__":
    main()
